### ISSUE TITLE
Butterscotch Cinnamon Pie spawns as "almost too rotten to eat"

### ISSUE THREAD

**Issue by baabaablackgoat** [baabaablackgoat/starboundgoats#18]
But it doesn't seem to decay, either.

**Comment by PieofCinder** [comment]
There is no ***Cinnamon*** on the pie's recipe. 
![screenshot_6](https://user-images.githubusercontent.com/46134678/53315808-edaeee80-38a3-11e9-81fe-839d3bf76950.png)
